package com.athrved.masterclass;

import java.util.ArrayList;

public class DataClass {
    public ArrayList<String> videoIds;
    ArrayList<String> vtitle;
    ArrayList<String> authorr;
    ArrayList<Integer> topic;
    ArrayList<Integer> course_id;
    ArrayList<Integer> paid;
    ArrayList<Integer> slno;


    public void getdatatotop() {
        videoIds = new ArrayList<>();
        course_id = new ArrayList<>();
        paid = new ArrayList<>();
        vtitle = new ArrayList<>();
        slno = new ArrayList<>();
        topic = new ArrayList<>();
        authorr = new ArrayList<>();


//  videoIds.add("");   course_id.add();    paid.add();     vtitle.add("");

//UIUX
        slno.add(1);        videoIds.add("SRec90j6lTY");        course_id.add(5);        paid.add(0);        authorr.add("Sudhanva");      topic.add(0);
        vtitle.add("Adobe XD Tutorial | Login/Signup Page | Basic Course of UI/UX Design");
        slno.add(2);
        videoIds.add("EBCn1btfX68");
        course_id.add(5);
        paid.add(0);
        authorr.add("Sushmitha");
        topic.add(0);
        vtitle.add("How to Learn UI/UX DESIGN online for FREE? (Explanation by a Designer");
        slno.add(3);
        videoIds.add("SbS1jwm4U4o");
        course_id.add(5);
        paid.add(0);
        authorr.add("Avish");
        topic.add(5);
        vtitle.add("What is User Experience (UX)");
        slno.add(4);
        videoIds.add("OdSgDir6XKs");
        course_id.add(5);
        paid.add(0);
        authorr.add("Avish");
        topic.add(0);
        vtitle.add("User Experience Research");
        slno.add(5);
        videoIds.add("JDMXgPCN-BM");
        course_id.add(5);
        paid.add(0);
        authorr.add("Ankith");
        topic.add(1);
        vtitle.add("User Research Interviews");
        slno.add(6);
        videoIds.add("UnAuwhu2C9Q");
        course_id.add(5);
        paid.add(0);
        authorr.add("Avish");
        topic.add(2);
        vtitle.add("User Persona for UX");
        slno.add(7);
        videoIds.add("6C2Ye1makdY");
        course_id.add(5);
        paid.add(0);
        authorr.add("Neeraj");
        topic.add(3);
        vtitle.add("Adobe XD how to Download and Install");
        slno.add(8);
        videoIds.add("n7-atYzJKTA");
        course_id.add(5);
        paid.add(0);
        authorr.add("Preetham");
        topic.add(4);
        vtitle.add("Adobe XD User Interface and Artboards");


//APP
        slno.add(1);
        videoIds.add("TnTn6e4Pfn8");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How to become an Android Developer | Step by Step | Freelancing and Placement");
        slno.add(2);
        videoIds.add("5soHbJrzuok");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Avish");
        vtitle.add("How Applications Are Made? | Android Development for Beginners | Basics of Android Development");
        slno.add(3);
        videoIds.add("InigFUSiPl8");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Installing Android Studio & Setup | Android Tutorials in Hindi #1");
        slno.add(4);
        videoIds.add("PoBePPh5Iko");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Ankith");
        vtitle.add("Creating Our First Android App (with APK) | Android Tutorials in Hindi #2");
        slno.add(5);
        videoIds.add("HHaghq5wXic");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Preetham");
        vtitle.add("Linear Layout & Relative Layout In Android | Android Tutorials in Hindi #3");
        slno.add(6);
        videoIds.add("jUmqYE2iWiI");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Android activity & Activity Lifecycle | Android Tutorials in Hindi #4");
        slno.add(7);
        videoIds.add("WVjqX1BoQeM");
        course_id.add(3);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Project 1: Tic Tac Toe Game Android Game Development | Android Tutorials in Hindi #5");

//MECH
        slno.add(1);
        videoIds.add("TnTn6e4Pfn8");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How to become an Android Developer | Step by Step | Freelancing and Placement");
        slno.add(2);
        videoIds.add("5soHbJrzuok");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How Applications Are Made? | Android Development for Beginners | Basics of Android Development");
        slno.add(3);
        videoIds.add("InigFUSiPl8");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Installing Android Studio & Setup | Android Tutorials in Hindi #1");
        slno.add(4);
        videoIds.add("PoBePPh5Iko");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Creating Our First Android App (with APK) | Android Tutorials in Hindi #2");
        slno.add(5);
        videoIds.add("HHaghq5wXic");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Linear Layout & Relative Layout In Android | Android Tutorials in Hindi #3");
        slno.add(6);
        videoIds.add("jUmqYE2iWiI");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Android activity & Activity Lifecycle | Android Tutorials in Hindi #4");
        slno.add(7);
        videoIds.add("WVjqX1BoQeM");
        course_id.add(4);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Project 1: Tic Tac Toe Game Android Game Development | Android Tutorials in Hindi #5");
//AI
        slno.add(1);
        videoIds.add("TnTn6e4Pfn8");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How to become an Android Developer | Step by Step | Freelancing and Placement");
        slno.add(2);
        videoIds.add("5soHbJrzuok");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How Applications Are Made? | Android Development for Beginners | Basics of Android Development");
        slno.add(3);
        videoIds.add("InigFUSiPl8");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Installing Android Studio & Setup | Android Tutorials in Hindi #1");
        slno.add(4);
        videoIds.add("PoBePPh5Iko");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Creating Our First Android App (with APK) | Android Tutorials in Hindi #2");
        slno.add(5);
        videoIds.add("HHaghq5wXic");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Linear Layout & Relative Layout In Android | Android Tutorials in Hindi #3");
        slno.add(6);
        videoIds.add("jUmqYE2iWiI");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Android activity & Activity Lifecycle | Android Tutorials in Hindi #4");
        slno.add(7);
        videoIds.add("WVjqX1BoQeM");
        course_id.add(1);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Project 1: Tic Tac Toe Game Android Game Development | Android Tutorials in Hindi #5");

//WEB
        slno.add(1);
        videoIds.add("TnTn6e4Pfn8");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How to become an Android Developer | Step by Step | Freelancing and Placement");
        slno.add(2);
        videoIds.add("5soHbJrzuok");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How Applications Are Made? | Android Development for Beginners | Basics of Android Development");
        slno.add(3);
        videoIds.add("InigFUSiPl8");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Installing Android Studio & Setup | Android Tutorials in Hindi #1");
        slno.add(4);
        videoIds.add("PoBePPh5Iko");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Creating Our First Android App (with APK) | Android Tutorials in Hindi #2");
        slno.add(5);
        videoIds.add("HHaghq5wXic");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Linear Layout & Relative Layout In Android | Android Tutorials in Hindi #3");
        slno.add(6);
        videoIds.add("jUmqYE2iWiI");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Android activity & Activity Lifecycle | Android Tutorials in Hindi #4");
        slno.add(7);
        videoIds.add("WVjqX1BoQeM");
        course_id.add(2);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Project 1: Tic Tac Toe Game Android Game Development | Android Tutorials in Hindi #5");

//IOT
        slno.add(1);
        videoIds.add("TnTn6e4Pfn8");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How to become an Android Developer | Step by Step | Freelancing and Placement");
        slno.add(2);
        videoIds.add("5soHbJrzuok");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("How Applications Are Made? | Android Development for Beginners | Basics of Android Development");
        slno.add(3);
        videoIds.add("InigFUSiPl8");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Installing Android Studio & Setup | Android Tutorials in Hindi #1");
        slno.add(4);
        videoIds.add("PoBePPh5Iko");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Creating Our First Android App (with APK) | Android Tutorials in Hindi #2");
        slno.add(5);
        videoIds.add("HHaghq5wXic");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Linear Layout & Relative Layout In Android | Android Tutorials in Hindi #3");
        slno.add(6);
        videoIds.add("jUmqYE2iWiI");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Android activity & Activity Lifecycle | Android Tutorials in Hindi #4");
        slno.add(7);
        videoIds.add("WVjqX1BoQeM");
        course_id.add(6);
        paid.add(0);
        topic.add(0);
        authorr.add("Sudhanva");
        vtitle.add("Project 1: Tic Tac Toe Game Android Game Development | Android Tutorials in Hindi #5");

    }

    }